if(!window.JAWS){var JAWS={};}
function forceLocalizationDonate(event){if(!readCookie('pbsol.station')){if(event.preventDefault)event.preventDefault();JAWS.Localization.init('Donate');}}
JAWS.Header=(function(){var headerOpts=JAWS.main.getWidgetData("header"),searchInput=document.querySelector("#header_query"),pbsLogo=Array.from(document.querySelectorAll('.pbs_loc_name')).find(node=>getComputedStyle(node.parentElement.parentElement)['display']!=='none'),headerLinks=document.querySelectorAll("#pbs_dh a"),searchForm=document.querySelector("#pbs_distribution_search_form"),btnLocal=document.querySelector("#btnLocalSearch"),btnGlobal=document.querySelector("#btnGlobalSearch"),btnSearchDropdown=document.querySelector("#pbs_lens"),searchDropdown=document.querySelector("#pbs_dh_search"),btnMenuDropdown=document.querySelector("#pbs_btn_dropdown"),pbsDropdown=document.querySelector("#pbs_dropdown"),btnDonate=document.querySelector(".donate-btn");if(headerOpts.local_search_url)
searchInput.setAttribute("data-type","local");function trackEvent(target,action,label){if(typeof GTMDataLayer!=="undefined"){GTMDataLayer.push({'event':'GlobalChrome','category':target,'action':action,'label':label});}}
function submitSearch(evt){var _this=evt.currentTarget,_type=_this.getAttribute("data-type"),_query=searchInput.value;if(_type==="local"){trackEvent("GlobalChrome_Header","Search","Search This Site");window.location=headerOpts.local_search_url+_query;}else if(_type==="global"){searchForm.setAttribute("action",headerOpts.global_search_url+_query);trackEvent("GlobalChrome_Header","Search","Search PBS");searchForm.submit();}}
function manageDropdowns(evt){var _this=evt.currentTarget,_type=_this.getAttribute("data-type");_this.jwToggleClass("active");if(_type==="search"){searchDropdown.jwToggleClass("active");pbsDropdown.jwRemoveClass("active");btnMenuDropdown.jwRemoveClass("active");btnMenuDropdown.setAttribute("aria-expanded","false");if(btnSearchDropdown.jwHasClass("active")){btnSearchDropdown.setAttribute("aria-expanded","true");}else{btnSearchDropdown.setAttribute("aria-expanded","false");}}else if(_type==="menu"){pbsDropdown.jwToggleClass("active");searchDropdown.jwRemoveClass("active");btnSearchDropdown.jwRemoveClass("active");btnSearchDropdown.setAttribute("aria-expanded","false");if(btnMenuDropdown.jwHasClass("active")){btnMenuDropdown.setAttribute("aria-expanded","true");}else{btnMenuDropdown.setAttribute("aria-expanded","false");}}
evt.preventDefault();}
function navigationTracking(evt){var _this=evt.currentTarget,_btnText=_this.innerHTML,_label="",_station=pbsLogo.querySelector("span").innerHTML,_destination=_this.getAttribute("href"),_needsTracking=_this.jwHasClass("ga");if(_needsTracking){_label=_btnText+" | "+_destination;if(_this.jwHasClass("donate-btn")){if(_station!==""){_label=_btnText+" | "+_station+" | "+
window.location.href;}}
if(_this.getAttribute("class")==="pbs_loc_name"){_label=_station+" | "+_this.getAttribute("href");}
trackEvent("GlobalChrome_Header","Link",_label);}}
if(headerOpts.hasOwnProperty('local_search_url')){btnLocal.jwOn("click",submitSearch);}
btnGlobal.jwOn("click",submitSearch);searchInput.jwOn("keypress",function(evt){if(evt.keyCode==13){submitSearch(evt);evt.preventDefault();}});btnSearchDropdown.jwOn("click",manageDropdowns);btnMenuDropdown.jwOn("click",manageDropdowns);for(var i=0;i<headerLinks.length;i++){headerLinks[i].jwOn("click",navigationTracking);}
if(!headerOpts.local_search_url){btnLocal.style.display="none";}
if(!headerOpts.global_search_url){btnGlobal.style.display="none";}}());if(document.addEventListener){document.addEventListener("confirmStationEvent",function(event){var data=event.detail||event.data;if(data&&data.donate=="Donate"){membership_url=event.data.link;confirmBtn=event.data.confirmBtn;document.querySelector(confirmBtn).click(window.open(membership_url,"_blank"));return false;}});}else{document.attachEvent("confirmStationEvent",function(event){var data=event.detail||event.data;if(data&&data.donate=="Donate"){membership_url=event.data.link;confirmBtn=event.data.confirmBtn;document.querySelector(confirmBtn).click(window.open(membership_url,"_blank"));return false;}});}