Element.prototype.jwAddClass=function(className){if(this.classList){this.classList.add(className);}else{this.className+=" "+className;}};Element.prototype.jwRemoveClass=function(className){if(this.classList){this.classList.remove(className);}else{this.className=this.className.replace(new RegExp("(^|\\b)"+
className.split(" ").join("|")+
"(\\b|$)","gi")," ");}};Element.prototype.jwToggleClass=function(className){if(this.classList){this.classList.toggle(className);}else{var classes=this.className.split(" ");var existingIndex=classes.indexOf(className);if(existingIndex>=0){classes.splice(existingIndex,1);}else{classes.push(className);}
this.className=classes.join(" ");}};Element.prototype.jwHasClass=function(className){if(this.classList){return this.classList.contains(className);}else{return new RegExp("(^| )"+className+
"( |$)","gi").test(this.className);}};Element.prototype.jwOn=function(eventName,callback,useCapture){this.addEventListener(eventName,callback,useCapture||false);};;if(!window.JAWS){var JAWS={};}
function Ajax(settings,callback){var jsonpScript=document.createElement("script"),jsonpCallbackFunction,XHR;var createXhrObject=function(){if(typeof XMLHttpRequest!=="undefined"){return new XMLHttpRequest();}
var versions=["MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0","Microsoft.XmlHttp"],versionsLength=versions.length,xhr,i;for(i=0;i<versionsLength;i++){try{xhr=new ActiveXObject(versions[i]);break;}catch(e){}}
return xhr;},getRequestData=function(data){var query=[];if(data){for(var i=0;i<Object.keys(data).length;i++){key=Object.keys(data)[i];query.push(encodeURIComponent(key)+"="+
encodeURIComponent(data[key]));}}
return query.join("&");},xhrError=function(){console.error(this.statusText);},send=function(url,callback,method,data,sync){XHR.open(method,url,sync);XHR.onreadystatechange=function(){if(XHR.readyState===4){if(XHR.status===200){callback(XHR.responseText);}}};XHR.onerror=this.xhrError;if(method==="POST"){this.XHR.setRequestHeader("Content-type","application/x-www-form-urlencoded");}
XHR.send(data);},evalJSONP=function(callback){return function(data){var validJSON=false;delete window[jsonpCallbackFunction];try{document.body.removeChild(jsonpScript);}catch(err){document.head.removeChild(jsonpScript);}
var responseJSON;if(typeof data=="string"){try{validJSON=JSON.parse(console.log(validJSON));responseJSON=validJSON;}catch(e){}}else{validJSON=JSON.parse(JSON.stringify(data));responseJSON=data;}
if(validJSON){callback(responseJSON);}else{throw("JSONP call returned invalid or empty JSON");}};},jsonp=function(url,callback){jsonpCallbackFunction="callbackfunction"+
Math.round(100000*Math.random());url+=(url.indexOf("?")!==-1?"&":"?")+"callback="+
jsonpCallbackFunction;window[jsonpCallbackFunction]=evalJSONP(callback);jsonpScript.type="text/javascript";jsonpScript.async=true;jsonpScript.src=url;if(!document.body){document.head.appendChild(jsonpScript);}else{document.body.appendChild(jsonpScript);}},init=function(settings,callback){var sync=settings.async||true,data=settings.data,query=getRequestData(data),url=settings.url;XHR=createXhrObject();if(settings.hasOwnProperty("xhrFields")){if(settings.xhrFields.hasOwnProperty("withCredentials")){XHR.withCredentials=true;}}
switch(settings.type){case"POST":send(url,callback,"POST",query,sync);break;case"JSON":send(url,callback,"GET",query,sync);break;case"JSONP":jsonp(url,callback);break;default:send(url+"?"+query,callback,"GET",null,sync);break;}};if(!settings.url){throw"No URL was specified";}
init(settings,callback);};if(!window.JAWS){window.JAWS={};}
if(!window.console){window.console={log:function(){'use strict';},warn:function(){'use strict';},error:function(){'use strict';}};}
(function(){if(typeof window.CustomEvent==="function")return false;function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};var evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt;}
CustomEvent.prototype=window.Event.prototype;window.CustomEvent=CustomEvent;})();JAWS.Localization=(function(){'use strict';var staExtended,redirect_to,serverUrl='//jaws.pbs.org/',donate_url='http://www.pbs.org/donate/',kidsCookie,stationCookie,stationIdCookie,preventOverlaysCookie,trackingCategory="Auto-localization overlay",filesLoaded=false,setOnce=false,initialCallSign=false,localizationType,modalOverlay,confirmOverlay,modalFind,modalConfirm,needsRefresh=false,post_data={},modalList,bodyElem=document.querySelector('body'),localizationUrl=serverUrl+'localization/',localizationZip=localizationUrl+'member/zip-code/',zipCode,donate,localizationData={},autoSelectedStation={},localizationCss=['//d2ok2u3bz752mp.cloudfront.net/prod/1.11.1/'+'css/localization.css'],logoProfile=getLogoProfilePref(),ajax;if(typeof trackEvent=='undefined'){window.trackEvent=function(target,action,label,nonInteraction){if(typeof GTMDataLayer!=="undefined"){var nonInteraction=nonInteraction?nonInteraction:false;GTMDataLayer.push({'event':'GlobalChrome','category':target,'action':action,'label':label,'nonInteraction':nonInteraction,});}}}
function getLogoProfilePref(){var callsignNodes=((document.querySelectorAll('.pbs_loc_name').length>0&&document.querySelectorAll('.pbs_loc_name'))||(document.querySelectorAll('.localize').length>0&&document.querySelectorAll('.localize'))),logoColor=callsignNodes&&callsignNodes[0].getAttribute("data-logo-color");if(logoColor&&logoColor==='white'){return'white';}
return'color';}
function getDomainName(hostName){return hostName.substring(hostName.lastIndexOf(".",hostName.lastIndexOf(".")-1));}
function createCookie(name,value,days){var expires="",domain=".pbs.org",date;if(days){date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toGMTString();}
if(window.location.hostname!==""){domain=getDomainName(window.location.hostname);}
document.cookie=name+"="+value+expires+"; path=/; domain="+domain;}
function readCookie(name){var nameEQ=name+"=",ca=document.cookie.split(';'),i,c;for(i=0;i<ca.length;i+=1){c=ca[i];while(c.charAt(0)===' '){c=c.substring(1,c.length);}
if(c.indexOf(nameEQ)===0){return c.substring(nameEQ.length,c.length);}}
return null;}
function eraseCookie(name){createCookie(name,"",-1);}
function isInteger(number){var regex=/^-?\d+$/;return regex.test(number);}
function cookieMonster(station){var pbsKidsImage=document.createElement('iframe');pbsKidsImage.src='//pbskids.org/localization/p.gif?pbs.station='+station;pbsKidsImage.style.display='none';document.body.appendChild(pbsKidsImage);}
function localizeUser(stationData){createCookie('pbsol.common.name.short',stationData.common_name_short,356);createCookie('pbsol.common.name',stationData.common_name,356);createCookie('pbsol.station',stationData.station,356);createCookie('pbsol.station_id',stationData.station_id,356);}
function setDonateLink(donateLink){var donateBtn=document.querySelector(".donate-btn");if(donateBtn&&donateLink){donateBtn.href=donateLink;}}
function setStationLogo(name,url,img_url){var stationNameNodes=document.querySelectorAll('.pbs_loc_name'),img;for(var stationName of stationNameNodes){if(stationName){img=stationName.querySelector('img');}
if(!img){img=document.createElement('img');}
img.srcset=img_url+'?resize=200x&format=png 1x,'+img_url+'?resize=400x&format=png 2x';img.src=img_url+'?resize=200x&format=png';img.alt=name;if(stationName){stationName.appendChild(img);stationName.href=url;stationName.jwAddClass("localize");}}}
function changeStationLogo(callsign){var logoHolder=document.querySelector('.modalStationImage');var regionalDefaultStation=document.querySelector('.regionalDefaultStation');var regionalDefaultStationMobile=document.querySelector('.regionalDefaultStationMobile');ajax=new Ajax({url:localizationUrl+"false/?callsign="+callsign,type:'JSONP'},function(data){logoHolder.innerHTML='<img src="'+data.station.logo_url+'"?resize=400x&format=png" alt="'+data.station.short_name+'">';if(regionalDefaultStation&&data.station.short_name){regionalDefaultStation.innerHTML=data.station.short_name;}
if(regionalDefaultStationMobile&&data.station.short_name){regionalDefaultStationMobile.innerHTML=data.station.short_name;}});}
function closest(el,fn){return el&&(fn(el)?el:closest(el.parentNode,fn));}
function selectStation(evt){var stationItems=document.querySelectorAll('#autoStationsList .stationItem'),that=evt.target,stationId,stationElem,stationCommonName;Array.prototype.forEach.call(stationItems,function(el){el.jwRemoveClass('active');el.setAttribute('aria-pressed','false');});stationElem=closest(that,function(el){return el.tagName.toLowerCase()==='button';});stationId=stationElem.id;stationElem.jwAddClass('active');stationElem.setAttribute('aria-pressed','true');stationCommonName=stationElem.getAttribute('data-common_name');changeStationLogo(stationId);}
function toggleElements(state){var noStations=document.querySelectorAll('.localizationStationListNoStations'),hasStations=document.querySelectorAll('.localizationStationList');if(!state){Array.prototype.forEach.call(noStations,function(el){el.jwRemoveClass('none');});Array.prototype.forEach.call(hasStations,function(el){el.jwAddClass('none');});}else if(state){Array.prototype.forEach.call(noStations,function(el){el.jwAddClass('none');});Array.prototype.forEach.call(hasStations,function(el){el.jwRemoveClass('none');});}}
function addStations(data){var defaultStation=data[0],stationHTML='',stationsLength=Object.keys(data).length,modalList=document.querySelector('#pbs-stations-list'),stationsSection=document.querySelector('#autoSelectStation'),stations=document.querySelector('#autoStationsList'),stationItems,index;toggleElements(true);if(stationsLength===0){toggleElements(false);trackEvent(trackingCategory,'No Stations for Zip','viewed step');}
if(defaultStation&&defaultStation.flagship){changeStationLogo(defaultStation.flagship);if(!setOnce&&localizationType==='forced'){localizeUser({'common_name':defaultStation.common_name,'common_name_short':defaultStation.common_name_short,'station':defaultStation.flagship,'station_id':defaultStation.id,'zipCode':defaultStation.zip_code});setOnce=true;}}
for(index=0;index<data.length;index+=1){stationHTML+='<button id="'+data[index].flagship+'" class="stationItem'+(index===0?' active':'')+'" data-donate_url="'+data[index].membership_url+'" data-common_name="'+data[index].common_name+'" data-zipcode="'+data[index].zip_code+'" aria-pressed="'+(index===0?'true':'false')+'">';stationHTML+='<h3><strong class="commonName">'+data[index].common_name+'</strong><strong class="shortCommonName">'+data[index].common_name_short+'</strong></h3>';stationHTML+='<span>'+data[index].address+'</span>';stationHTML+='</button>';}
stations.innerHTML=stationHTML;stationsSection.jwRemoveClass('none');stationItems=stations.querySelectorAll('.stationItem');Array.prototype.forEach.call(stationItems,function(el){el.addEventListener('click',selectStation);});}
function loadStylesheets(urls,callback){var link;Array.prototype.forEach.call(urls,function(key){var cacheBuster='?'+(new Date()).getTime();link=document.createElement("link");link.rel="stylesheet";link.type="text/css";link.href=key+cacheBuster;if(callback){link.addEventListener('load',callback);}
document.head.appendChild(link);});filesLoaded=true;}
function insertContent(html){var container;if(typeof html==="undefined"){throw"No html has specified";}
container=document.querySelector("#jaws_localization");if(!container){container=document.createElement("div");container.className="pbs-cleanslate";container.id="jaws_localization";}
container.innerHTML=html;document.body.insertBefore(container,document.body.firstChild);}
function passFocusOnClose(){var passFocusToOnClose=bodyElem.getAttribute('data-pass-focus-to-on-close');var targetElem=document.getElementById(passFocusToOnClose);var targetIsVisible=targetElem&&targetElem.offsetHeight!==0;if(!targetIsVisible){targetElem=bodyElem;}
targetElem.focus();bodyElem.removeAttribute('data-pass-focus-to-on-close');}
function switchModals(state){var localization_widget,activeStationListItem=document.querySelector('#autoStationsList .stationItem.active');modalFind=document.querySelector('#pbs-find-stations');modalList=document.querySelector('#pbs-stations-list');modalConfirm=document.querySelector('#pbs-confirm-station');switch(state){case'list':modalFind.jwAddClass('none');modalConfirm.jwAddClass('none');modalList.jwRemoveClass('none');modalOverlay.jwRemoveClass('none');confirmOverlay.jwAddClass('none');trackEvent(trackingCategory,'Confirm Station','Viewed Overlay');modalList.focus();window.addEventListener('keyup',closeOnEscape);modalList.addEventListener('keydown',onKeyDown);break;case'find':modalList.jwAddClass('none');modalConfirm.jwAddClass('none');modalFind.jwRemoveClass('none');modalOverlay.jwRemoveClass('none');confirmOverlay.jwAddClass('none');if(activeStationListItem){activeStationListItem.jwRemoveClass('active');}
trackEvent(trackingCategory,'Find Station','viewed step');modalFind.focus();modalList.removeEventListener('keydown',onKeyDown);window.addEventListener('keyup',closeOnEscape);modalFind.addEventListener('keydown',function(evt){if(evt.target===modalFind){onKeyDown(evt);}});break;case'confirm':modalOverlay.jwAddClass('none');confirmOverlay.jwRemoveClass('none');modalConfirm.jwRemoveClass('none');positionConfirmModal();bodyElem.style.overflow='auto';break;default:if(modalList){modalList.jwAddClass('none');}
if(modalFind){modalFind.jwAddClass('none');}
if(modalConfirm){modalConfirm.jwAddClass('none');}
localization_widget=document.querySelector('#jaws_localization');if(localization_widget){localization_widget.parentNode.removeChild(localization_widget);}
bodyElem.style.overflow='auto';passFocusOnClose();window.removeEventListener('keyup',closeOnEscape);}}
function createEvent(name,evData,bubbles,cancelable){var ev;if(window.CustomEvent){ev=new CustomEvent(name,{detail:evData||{},data:evData||{},bubbles:bubbles||true,cancelable:cancelable||true});}else{if(document.createEvent){ev=document.createEvent("HTMLEvents");ev.initEvent(name,bubbles||true,cancelable||true);}else{ev=document.createEventObject();ev.eventType=name;}
ev.eventName=name;ev.data=evData||{};}
return ev;}
function fireEvent(evt){if(document.createEvent){document.dispatchEvent(evt);}else{document.fireEvent("on"+evt.eventType,evt);}}
function onKeyDown(evt){var el=evt.target;var tabKeyCode=9;var returnKeyCode=13;var spaceKeyCode=32;var tabFocusTarget=el.getAttribute('data-pass-focus-on-tab-to');var shiftTabFocusTarget=el.getAttribute('data-pass-focus-on-shift-tab-to');if(evt.keyCode===returnKeyCode||evt.keyCode===spaceKeyCode){prepareToClose(evt);return;}
if(evt.keyCode===tabKeyCode){if(evt.shiftKey&&shiftTabFocusTarget){evt.preventDefault();document.getElementById(shiftTabFocusTarget).focus();}else if(!evt.shiftKey&&tabFocusTarget){evt.preventDefault();document.getElementById(tabFocusTarget).focus();}}}
function closeOnEscape(evt){var escKeyCode=27;var selectedStation=document.querySelector('#autoStationsList .stationItem.active');var modalFind=document.querySelector('#pbs-find-stations');var modalList=document.querySelector('#pbs-stations-list');var confirmOverlay=document.querySelector('#pbs-confirm-station');if(evt.keyCode===escKeyCode){if(needsRefresh){prepareToClose(evt,true);}else{switchModals();}}}
function prepareToClose(evt,initLocalize){var that=evt.target,selectedStation=document.querySelector('#autoStationsList .stationItem.active'),station,stationList=Array.prototype.slice.call(document.getElementById('autoStationsList').children);function callback(){if(redirect_to){window.location.href=redirect_to;}else{if(!that.getAttribute('data-noreload')){location.reload();}else{switchModals();}}}
function onFindStationsClose(){if(needsRefresh){trackEvent(trackingCategory,'Find Station','Close');callback();}else{trackingCategory="See more Stations – Localization Overlay";trackEvent(trackingCategory,'Find Station','Close');switchModals();}}
function handleButtonAction(stationData){if(that.getAttribute('class')==='closeBtn'){if(localizationType==='forced'){if(selectedStation){trackEvent(trackingCategory,'Close',selectedStation.getAttribute('id')+' - '+parseInt(stationList.indexOf(selectedStation)+1));}
else{if(document.querySelector('#autoStationsList .stationItem'))
trackEvent(trackingCategory,'Find Station','Close');else
trackEvent(trackingCategory,'No Stations for Zip','Close');evt.preventDefault();callback();return false;}
evt.preventDefault();callback();}
if(localizationType==='manual'){if(selectedStation){trackEvent(trackingCategory,'Close',selectedStation.id+' - '+(stationList.indexOf(selectedStation)+1));}
else{if(document.querySelector('#autoStationsList .stationItem')||document.querySelector('.localizationStationListNoStations').offsetHeight==0)
trackEvent(trackingCategory,'Find Station','Close');else
trackEvent(trackingCategory,'No Stations for Zip','Close');}
switchModals();}
if(redirect_to){window.location.href=redirect_to;}}
if(that.id==='confirmStation'||that.getAttribute('data-confirm-station')==='true'||initLocalize){if(typeof evt.keyCode==='undefined'&&evt.detail==0){if(evt.pointerId!=1)
return;}
if(!that.getAttribute('data-ga-event')){trackEvent(trackingCategory,'Confirm',selectedStation.id+' - '+parseInt(stationList.indexOf(selectedStation)+1));}else{trackEvent(trackingCategory,'Is This Your Station',that.getAttribute('data-ga-event')+' - '+initialCallSign);}
localizeUser(station);var confirmEvent=createEvent('confirmStationEvent',{link:stationData.donate_url,zipCode:stationData.zip_code,confirmBtn:that.getAttribute('id')?"#"+that.getAttribute('id'):'',donate:donate,station:stationData.call_sign});fireEvent(confirmEvent);var donate_location="jaws.lunchbox.pbs.org";evt.preventDefault();callback();}}
if(selectedStation){var ajax=new Ajax({url:localizationUrl+'false/?callsign='+selectedStation.getAttribute('id'),type:'JSONP'},function(data){var stationData=data.station.skylab_data;station={'common_name':stationData.full_common_name,'common_name_short':stationData.short_common_name,'station_id':stationData.id,'station':stationData.call_sign,'zipCode':stationData.zip_code,'donate_url':stationData.donate_url,'tvss_url':stationData.tvss_url};handleButtonAction(stationData);});}else if(that.id==='pbs-close-find-station'){onFindStationsClose();}else if(needsRefresh){callback();}else{switchModals();}}
function localizeState(){var stateSelect=document.querySelector('#regionSelect'),state=stateSelect.value,stateError=stateSelect.parentElement.querySelector('.errorMsg'),ajax;stateError.jwAddClass("none");stateSelect.jwRemoveClass("invalid");if(state!==''){trackEvent(trackingCategory,'Find Station',"Search by state - "+state);ajax=new Ajax({url:localizationUrl+'member/state/'+state+'/',type:'JSONP'},function(data){addStations(data.stations_list);switchModals('list');});}else{stateError.jwRemoveClass("none");stateSelect.jwAddClass("invalid");return false;}}
function localizeZip(){var zipValue=document.querySelector('#zipInput').value,zipError=document.querySelector('#zipInput').parentElement.querySelector('.errorMsg'),zipCode=document.querySelector('#zipInput'),isValidZip=/(^\d{5}$)/.test(zipValue),ajax;zipError.jwAddClass("none");zipCode.jwRemoveClass("invalid");if(zipValue===""){zipError.innerHTML="Please enter a valid ZIP Code";zipError.jwRemoveClass("none");zipCode.jwAddClass("invalid");return false;}
if(!isValidZip){if(!isInteger(zipValue)){zipError.innerHTML='ZIP Code is not numeric';zipError.jwRemoveClass("none");zipCode.jwAddClass("invalid");return false;}
if(zipValue.toString().length<=4){zipError.innerHTML='ZIP Code too short';zipError.jwRemoveClass("none");zipCode.jwAddClass("invalid");return false;}}else{trackEvent(trackingCategory,'Find Station',"Search by ZIP - "+zipValue);ajax=new Ajax({url:localizationUrl+'member/zip-code/'+zipValue+'/',type:'JSONP'},function(data){addStations(data.stations_list);switchModals('list');zipCode=zipValue;});}}
function positionConfirmModal(){var confirmBox=document.querySelector('#pbs-confirm-station');if(!confirmBox){return;}
var arrowBox=confirmBox.querySelectorAll('.arrow-box')[0],before=confirmBox.querySelectorAll('.before')[0],callsignNodes=((document.querySelectorAll('.pbs_loc_name').length>0&&document.querySelectorAll('.pbs_loc_name'))||(document.querySelectorAll('.localize').length>0&&document.querySelectorAll('.localize'))),callsign=Array.from(callsignNodes).find(node=>getComputedStyle(node.parentElement.parentElement)['display']!=='none'),callsignWidth=callsign.offsetWidth;callsign.parentElement.insertBefore(confirmBox,callsign);function positionBox(){var callsignLeft=callsign.offsetLeft;before.jwRemoveClass('top-right');before.jwRemoveClass('top-left');if(callsignLeft+callsignWidth<document.body.offsetWidth/2){before.jwAddClass('top-left');confirmBox.style.textAlign='left';arrowBox.style.marginLeft=callsign.offsetLeft-before.offsetLeft+callsign.offsetWidth/2+'px';arrowBox.style.marginRight='0px';}else{before.jwAddClass('top-right');confirmBox.style.textAlign='right';arrowBox.style.marginLeft='0px';arrowBox.style.marginRight=(arrowBox.offsetParent.offsetWidth-callsign.offsetLeft-callsign.offsetWidth)-
(arrowBox.offsetWidth-before.offsetLeft-before.offsetWidth)+
callsign.offsetWidth/2+'px';}}
window.addEventListener('resize',positionBox);positionBox();}
function createOverlay(state){var closeBtn,confirmBtn,moreStations,searchByZip,searchByState,initialShortCommonName,confirmCallsign,confirmButton,changeStations,backBtn;if(localizationData.localization_overlay!==''){insertContent(localizationData.localization_overlay);if(localizationData.stations_list.length>0){addStations(localizationData.stations_list);confirmCallsign=document.querySelectorAll('.confirmCallsign');initialShortCommonName=localizationData.stations_list[0].common_name_short;initialCallSign=localizationData.stations_list[0].callsign;for(var i=0;i<confirmCallsign.length;i++){confirmCallsign[i].innerHTML=initialShortCommonName;}}
closeBtn=document.querySelectorAll('.closeBtn, .close');changeStations=document.querySelectorAll('.changeStation');moreStations=document.querySelectorAll('.showStatesModal');confirmBtn=document.querySelectorAll('.modalConfirmStation');modalOverlay=document.querySelector('#pbs-modal-overlay');confirmOverlay=document.querySelector('#pbs-confirm-modal-overlay');searchByZip=document.querySelector('#searchByZip');searchByState=document.querySelector('#serchByRegion');backBtn=document.querySelector('#backButton');Array.prototype.forEach.call(closeBtn,function(el){el.addEventListener('click',prepareToClose);el.addEventListener('keydown',onKeyDown);});Array.prototype.forEach.call(confirmBtn,function(el){el.addEventListener('click',prepareToClose);el.addEventListener('keydown',onKeyDown);});Array.prototype.forEach.call(changeStations,function(el){el.addEventListener('click',function(evt){var errors=document.querySelectorAll(".errorMsg"),i,stationListItem=document.querySelector('#autoStationsList .active');for(i=0;i<errors.length;i+=1){errors[i].jwAddClass("none");}
trackEvent(trackingCategory,'Is This Your Station','Change - '+initialCallSign);switchModals('list');evt.preventDefault();});});Array.prototype.forEach.call(moreStations,function(el){el.addEventListener('click',function(evt){trackEvent(trackingCategory,'More Stations','');createOverlay('find');});});searchByZip.addEventListener('click',localizeZip);searchByState.addEventListener('click',localizeState);backBtn.addEventListener('click',function(evt){switchModals('find');evt.preventDefault();});bodyElem.style.overflow='hidden';switchModals(state);}}
function autolocalize(){var url=localizationUrl+'true/',ajax;if(stationCookie){url+="?callsign="+stationCookie;}else{if(post_data&&post_data.extended){url+='?extended='+JSON.stringify(post_data);}}
window.skipAutoLocalization=true;ajax=new Ajax({url:url,type:'JSONP'},function(data){localizationType='forced';localizationData=data;var callsign=localizationData.stations_list[0].flagship;createCookie("pbs.preventOverlays",1,0);ajax=new Ajax({url:localizationUrl+"false/?callsign="+callsign+"&profile="+logoProfile,type:'JSONP'},function(data){autoSelectedStation=data.station;zipCode=autoSelectedStation.zip_code;var localizedEv=createEvent('jaws.localized',{station:autoSelectedStation});setStationLogo(autoSelectedStation.short_name,autoSelectedStation.site_address,autoSelectedStation.logo_url);setDonateLink(autoSelectedStation.membership_url);needsRefresh=true;createOverlay('confirm');fireEvent(localizedEv);var confirmBox=document.querySelector('#pbs-confirm-station-box');confirmBox.focus();trackEvent(trackingCategory,'Is This Your Station','Viewed Overlay',true);confirmBox.addEventListener('keydown',function(evt){if(evt.target===confirmBox){onKeyDown(evt);}});window.addEventListener('keyup',closeOnEscape);});});}
function init(popup_location,redirect_url){redirect_to=redirect_url||null;popup_location=popup_location||'';donate=popup_location;trackingCategory="See more Stations – Localization Overlay";var url=localizationUrl+'true/',ajax;initCookieData();if(stationCookie){if(post_data&&post_data.extended){url+='?extended='+JSON.stringify(post_data);}else{url+="?callsign="+stationCookie;}}
if(['Donate','TVSchedules','PassportVideos'].indexOf(popup_location)>-1){url+=(stationCookie?'&':'?')+'popup_location='+popup_location;}
ajax=new Ajax({url:url,type:'JSONP'},function(data){localizationData=data;localizationType='manual';zipCode=data.zip||zipCode;if(staExtended&&!popup_location){createOverlay('list');}else{createOverlay('find');}});}
function processStaExtendedCookie(key){var cookieData=staExtended,cookieArray=decodeURIComponent(cookieData).split('#'),regex=new RegExp("^"+key+"=","g"),data;Array.prototype.forEach.call(cookieArray,function(v){if(regex.test(v)){var temp=v.split('=');data=temp[1];data=data.replace('[','');data=data.replace(']','');data=data.replace(/"/g,'');data=data.split(',');}});return data;}
function initCookieData(){staExtended=readCookie('pbsol.sta_extended');kidsCookie=readCookie('pbskids.localized');stationCookie=readCookie('pbsol.station');stationIdCookie=readCookie('pbsol.station_id');preventOverlaysCookie=readCookie('pbs.preventOverlays');if(staExtended){post_data.extended={zip:processStaExtendedCookie("z")[0],state:processStaExtendedCookie("st")[0],stations:processStaExtendedCookie("s")};}}
initCookieData();if(!filesLoaded){loadStylesheets(localizationCss,function(){if(!window.hide_forced_localization){if(!window.skipAutoLocalization){if(staExtended&&!stationCookie){autolocalize();}}}});}
if(stationCookie){post_data.callsign=stationCookie;ajax=new Ajax({url:localizationUrl+"false/?callsign="+stationCookie+"&profile="+logoProfile,type:'JSONP'},function(data){var site_address=data.station.site_address||data.station.stationfinder_url;setStationLogo(data.station.short_name,site_address,data.station.logo_url);setDonateLink(data.station.membership_url);if(!stationIdCookie){createCookie('pbsol.station_id',data.station.skylab_data.id,356);}});}
if(stationCookie&&stationCookie!==kidsCookie){cookieMonster(stationCookie);createCookie('pbskids.localized',stationCookie,30);}
return{init:init};}());var GlobalChrome={'Localization':{'Init':function(){'use strict';JAWS.Localization.init();}}};